/// <reference types="cypress" />

import { faker } from '@faker-js/faker'

describe('Cadastro de checkout-one', () => {

    beforeEach(() => {
        cy.visit('https://automationpratice.com.br/checkout-one');

    });

    it('Cadastro de faturamento com sucesso', () => {
        cy.get('#fname')
            .should('be.visible')
            .type(faker.person.firstName())
        cy.get('#lname')
            .should('be.visible')
            .type(faker.person.lastName())
        cy.get('#cname')
            .should('be.visible')
            .type(faker.company.name())
        cy.get('#email')
            .type(faker.internet.email())
        cy.get('#country')
            .select(1)
        cy.get('#city')
            .select(1)
        cy.get('#zip')
            .type(faker.location.zipCode())
        cy.get('#faddress')
            .type(faker.location.streetAddress())
        cy.get('#messages')
            .type(faker.lorem.slug(5))
        cy.get('#materialUnchecked')
            .check()
        cy.get('.checkout-area-bg > .theme-btn-one')
            .click()
        cy.get(':nth-child(2) > h3')
            .should('have.text', 'Billings Information registred with success!')
        cy.get('#headingThree > div > [name="payment"]').check()
        cy.get(':nth-child(2) > :nth-child(2) > .theme-btn-one').click()
        cy.get('h2').should('have.text', 'Order success!')
        cy.get('body > div.fade.modal.show > div > div > div > div > div > div > div.col-lg-12 > div > div.col-lg-7.col-md-6 > div > h3')
            .should('have.text', 'Congrats! Your order was created with sucess!')
    });

    it('Cadsatro de checkout sem firstName ', () => {

        cy.get('#lname')
            .type(faker.person.lastName())
        cy.get('#cname')
            .type(faker.company.name())
        cy.get('#email')
            .should('be.visible')
        cy.get('#email')
            .type(faker.internet.email())
        cy.get('#country')
            .select(1)
        cy.get('#city')
            .select(1)
        cy.get('#zip')
            .type(faker.location.zipCode())
        cy.get('#faddress')
            .type(faker.location.streetAddress())
        cy.get('#messages')
            .type(faker.lorem.slug(5))
        cy.get('#materialUnchecked')
            .check()
        cy.get('.checkout-area-bg > .theme-btn-one')
            .click()
        cy.get(':nth-child(2) > h3')
            .should('have.text', 'Billings Information registred with success!')
        cy.get('#errorMessageFirstName').should('have.text', 'O campo First Name deve ser prenchido')
    });

    it('Cadastro de checkout sem lastName', () => {
        cy.get('#fname')
            .should('be.visible')
            .type(faker.person.firstName())
        cy.get('#cname')
            .type(faker.company.name())
        cy.get('#email')
            .should('be.visible')
        cy.get('#email')
            .type(faker.internet.email())
        cy.get('#country')
            .select(1)
        cy.get('#city')
            .select(1)
        cy.get('#zip')
            .type(faker.location.zipCode())
        cy.get('#faddress')
            .type(faker.location.streetAddress())
        cy.get('#messages')
            .type(faker.lorem.slug(5))
        cy.get('#materialUnchecked')
            .check()
        cy.get('.checkout-area-bg > .theme-btn-one')
            .click()
        cy.get(':nth-child(2) > h3')
            .should('have.text', 'Billings Information registred with success!')
        cy.get('#errorMessageFirstName').should('have.text', 'O campo Last Name deve ser prenchido')
    });

    it('Cadastro de checkout sem companyName', () => {
        cy.get('#fname')
            .should('be.visible')
            .type(faker.person.firstName())
        cy.get('#lname')
            .should('be.visible')
            .type(faker.person.lastName())
        cy.get('#email')
            .type(faker.internet.email())
        cy.get('#country')
            .select(1)
        cy.get('#city')
            .select(1)
        cy.get('#zip')
            .type(faker.location.zipCode())
        cy.get('#faddress')
            .type(faker.location.streetAddress())
        cy.get('#messages')
            .type(faker.lorem.slug(5))
        cy.get('#materialUnchecked')
            .check()
        cy.get('.checkout-area-bg > .theme-btn-one')
            .click()
        cy.get(':nth-child(2) > h3')
            .should('have.text', 'Billings Information registred with success!')
        cy.get('#headingThree > div > [name="payment"]').check()
        cy.get(':nth-child(2) > :nth-child(2) > .theme-btn-one').click()
        cy.get('h2').should('have.text', 'Order success!')
        cy.get('body > div.fade.modal.show > div > div > div > div > div > div > div.col-lg-12 > div > div.col-lg-7.col-md-6 > div > h3')
            .should('have.text', 'Congrats! Your order was created with sucess!')
    });

    it('Cadastro de checkout sem emailAddress', () => {
        cy.get('#fname')
            .should('be.visible')
            .type(faker.person.firstName())
        cy.get('#lname')
            .should('be.visible')
            .type(faker.person.lastName())
        cy.get('#cname')
            .should('be.visible')
            .type(faker.company.name())
        cy.get('#country')
            .select(1)
        cy.get('#city')
            .select(1)
        cy.get('#zip')
            .type(faker.location.zipCode())
        cy.get('#faddress')
            .type(faker.location.streetAddress())
        cy.get('#messages')
            .type(faker.lorem.slug(5))
        cy.get('#materialUnchecked')
            .check()
        cy.get('.checkout-area-bg > .theme-btn-one')
            .click()
        cy.get(':nth-child(2) > :nth-child(2) > .theme-btn-one').click()
        cy.get('#errorMessageFirstName').should('have.text', 'O campo E-mail deve ser prenchido ou é inválido')
    });

    it('Cadastro de checkout sem country', () => {
        cy.get('#fname')
            .should('be.visible')
            .type(faker.person.firstName())
        cy.get('#lname')
            .should('be.visible')
            .type(faker.person.lastName())
        cy.get('#cname')
            .should('be.visible')
            .type(faker.company.name())
        cy.get('#email')
            .type(faker.internet.email())
        cy.get('#city')
            .select(1)
        cy.get('#zip')
            .type(faker.location.zipCode())
        cy.get('#faddress')
            .type(faker.location.streetAddress())
        cy.get('#messages')
            .type(faker.lorem.slug(5))
        cy.get('#materialUnchecked')
            .check()
        cy.get('.checkout-area-bg > .theme-btn-one')
            .click()
        cy.get('#errorMessageFirstName').should('have.text', 'O campo Country deve ser prenchido')
    });

    it('Cadastro de checkout sem state/city', () => {
        cy.get('#fname')
            .should('be.visible')
            .type(faker.person.firstName())
        cy.get('#lname')
            .should('be.visible')
            .type(faker.person.lastName())
        cy.get('#cname')
            .should('be.visible')
            .type(faker.company.name())
        cy.get('#email')
            .type(faker.internet.email())
        cy.get('#country')
            .select(1)
        cy.get('#zip')
            .type(faker.location.zipCode())
        cy.get('#faddress')
            .type(faker.location.streetAddress())
        cy.get('#messages')
            .type(faker.lorem.slug(5))
        cy.get('#materialUnchecked')
            .check()
        cy.get('.checkout-area-bg > .theme-btn-one')
            .click()
        cy.get('#errorMessageFirstName').should('have.text', 'O campo City deve ser prenchido')
    });

    it('Cadastro de chekcout sem zip code', () => {
        cy.get('#fname')
            .should('be.visible')
            .type(faker.person.firstName())
        cy.get('#lname')
            .should('be.visible')
            .type(faker.person.lastName())
        cy.get('#cname')
            .should('be.visible')
            .type(faker.company.name())
        cy.get('#email')
            .type(faker.internet.email())
        cy.get('#country')
            .select(1)
        cy.get('#city')
            .select(1)
        cy.get('#faddress')
            .type(faker.location.streetAddress())
        cy.get('#messages')
            .type(faker.lorem.slug(5))
        cy.get('#materialUnchecked')
            .check()
        cy.get('.checkout-area-bg > .theme-btn-one')
            .click()
        cy.get('#errorMessageFirstName').should('have.text', 'O campo Zip Code deve ser prenchido')
    });

    it('Cadastro de checkout sem full address', () => {
        cy.get('#fname')
            .should('be.visible')
            .type(faker.person.firstName())
        cy.get('#lname')
            .should('be.visible')
            .type(faker.person.lastName())
        cy.get('#cname')
            .should('be.visible')
            .type(faker.company.name())
        cy.get('#email')
            .type(faker.internet.email())
        cy.get('#country')
            .select(1)
        cy.get('#city')
            .select(1)
        cy.get('#zip')
            .type(faker.location.zipCode())
        cy.get('#messages')
            .type(faker.lorem.slug(5))
        cy.get('#materialUnchecked')
            .check()
        cy.get('.checkout-area-bg > .theme-btn-one')
            .click()
        cy.get('#errorMessageFirstName').should('have.text', 'O campo Address deve ser prenchido')
    });

    it('Cadastro de checkout sem additional notes', () => {
        cy.get('#fname')
            .should('be.visible')
            .type(faker.person.firstName())
        cy.get('#lname')
            .should('be.visible')
            .type(faker.person.lastName())
        cy.get('#cname')
            .should('be.visible')
            .type(faker.company.name())
        cy.get('#email')
            .type(faker.internet.email())
        cy.get('#country')
            .select(1)
        cy.get('#city')
            .select(1)
        cy.get('#zip')
            .type(faker.location.zipCode())
        cy.get('#faddress')
            .type(faker.location.streetAddress())
        cy.get('#materialUnchecked')
            .check()
        cy.get('.checkout-area-bg > .theme-btn-one')
            .click()
        cy.get('#errorMessageFirstName').should('have.text', 'O campo Additional Notes deve ser prenchido')
    });

    it('Cadastro de pagamento com Direct Bank Transfer sem informar dados Billing Information', () => {
        cy.get('#headingOne > div > [name="payment"]').click()
        cy.get('#collapseOne > .payment_body > p')
            .should('be.visible')
            .should('have.text', 'Direct Bank Transfer')
        cy.get(':nth-child(2) > :nth-child(2) > .theme-btn-one').click()
        cy.get('#errorMessageFirstName').should('have.text', 'Preencha os dados de pagamento!')
    });

    it('Cadastro de pagamento com Mobile Banking sem informar dados Billing Information', () => {
        cy.get('#headingTwo > div > [name="payment"]').click()
        cy.get('#collapseTwo > .payment_body > p')
            .should('be.visible')
            .should('have.text', 'Direct Mobile Transfer')
        cy.get(':nth-child(2) > :nth-child(2) > .theme-btn-one').click()
        cy.get('#errorMessageFirstName').should('have.text', 'Preencha os dados de pagamento!')
    });

    it('Cadastro de pagamento com paypal sem informar dados Billing Information', () => {
        cy.get('#headingThree > div > [name="payment"]').click()
        cy.get('#collapseThree > .payment_body > p')
            .should('be.visible')
            .should('have.text', 'Some placeholder content for the second accordion panel. This panel is hidden by default.')
        cy.get(':nth-child(2) > :nth-child(2) > .theme-btn-one').click()
        cy.get('#errorMessageFirstName').should('have.text', 'Preencha os dados de pagamento!')
    });
});